In [1]:
import torch

In [3]:
# tensors

##1. Number
t1 = torch.tensor(4.)   # 4. or 4.0
t1.dtype

torch.float32

In [5]:
#2. vector
t2 = torch.tensor([1., 2, 3, 4])
t2 # each element gains same data type

tensor([1., 2., 3., 4.])

In [6]:
#3. matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
#4. 3D array
t4 = torch.tensor([[[11, 12, 13],
                  [13, 14, 15]],
                  [[15, 16, 17],
                  [17, 18, 19.]]])

t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [10]:
t1.shape

torch.Size([])

In [12]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [13]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [14]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [16]:
# Tensor Operations

# Making The Tensors

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [17]:
y = w * x + b 
y

tensor(17., grad_fn=<AddBackward0>)

In [18]:
# compute derivatives

y.backward()

In [19]:
# Display Gradients

print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [21]:
# with numpy

import numpy as np
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [24]:
# convert numpy array to torch tensor

y = torch.from_numpy(x) # works on original
# or 
y = torch.tensor(x)  # creates a copy of data
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [25]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [26]:
# convert torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])